version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/common-lib"
    schedule:
      interval: "daily"
    groups:
      maven-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: ".devcontainer/"
    schedule:
      interval: "daily"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      pre-commit-hooks:
        patterns:
          - "*"